### ISSUE TITLE
Installation conflict with jaraco.functools

### ISSUE THREAD

**Issue by 0-wiz-0** [jaraco/jaraco.itertools#9]
Both jaraco.functools and this install ${PYSITELIB}/jaraco/__init__.py - this is a problem for packaging systems which install all packages into the same prefix and want to register a file for one package only. Please solve this conflict.
Filed for both projects, see https://github.com/jaraco/jaraco.functools/issues/16

**Comment by jaraco** [comment]
See jaraco.functools for an explanation.
